name: Lint checks
on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json
      - name: Install composer dependencies
        run: composer install
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: ./node_modules/.bin/eslint . --ext .js,.vue resources/
      - name: Build dist
        run: npm run prod