name: Lint checks
on:
  push:
    branches: [ 'github-actions' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:
    branches: [ 'github-actions' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: ./node_modules/.bin/eslint resources --ext .js,.vue